name: field_captain
description: "Offline organizer for amateur football matches."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  drift: ^2.28.1
  fl_chart: ^1.0.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  package_info_plus: ^8.0.2
  path_provider: ^2.1.5
  provider: ^6.1.1
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: ^0.5.20
  table_calendar: ^3.2.0
  workmanager: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.28.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: "assets/fonts/OpenSans-VariableFont_wdth,wght.ttf"
          weight: 400
        - asset: "assets/fonts/OpenSans-VariableFont_wdth,wght.ttf"
          weight: 600

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.jpg"
  adaptive_icon_background: "#FFFFFF00"
  adaptive_icon_foreground: "assets/icons/icon.jpg"
